# Generated by Django 4.2.30 on 2026-09-25 03:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syslog_port', models.PositiveIntegerField(default=514, help_text='UDP and TCP port the syslog listener accepts messages on.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('syslog_retention_days', models.PositiveIntegerField(default=30, help_text='Messages older than this are deleted automatically.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('backup_frequency', models.CharField(choices=[('disabled', 'Disabled'), ('hourly', 'Every hour'), ('6h', 'Every 6 hours'), ('12h', 'Every 12 hours'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('backup_time', models.TimeField(default=datetime.time(2, 0), help_text='Time of day for daily and weekly backups (server time).')),
                ('backup_weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6)),
                ('backup_retention', models.PositiveIntegerField(default=30, help_text='How many backups to keep per switch.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('email_enabled', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('smtp_security', models.CharField(choices=[('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS'), ('none', 'None')], default='starttls', max_length=10)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('email_from', models.EmailField(blank=True, max_length=254)),
                ('email_recipients', models.TextField(blank=True, help_text='One address per line, or separated by commas.')),
                ('notify_backup_failed', models.BooleanField(default=True)),
                ('notify_config_changed', models.BooleanField(default=True)),
                ('listener_port', models.PositiveIntegerField(blank=True, null=True)),
                ('listener_error', models.CharField(blank=True, max_length=500)),
                ('listener_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'system settings',
                'verbose_name_plural': 'system settings',
            },
        ),
    ]
