# Generated by Django 5.2.17 on 2026-09-28 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='backup_retention',
            field=models.PositiveIntegerField(default=30, help_text='How many backups to keep per network device.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
