# Generated by Django 4.2.30 on 2026-09-25 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_vendor_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('config', models.TextField(blank=True)),
                ('config_hash', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('changed', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='inventory.device')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['device', '-created'], name='backups_con_device__bb07b7_idx')],
            },
        ),
    ]
