# Generated by Django 4.2.11 on 2026-04-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(default='10.0.0.0'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
