# Generated by Django 4.2.11 on 2026-04-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_device_ip_address_alter_device_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
