# Generated by Django 4.2.11 on 2026-04-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_location_vendor_alter_device_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
