# Generated by Django 4.2.30 on 2026-09-25 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_vendor_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyslogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(db_index=True)),
                ('source_ip', models.GenericIPAddressField(db_index=True)),
                ('facility', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('severity', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Emergency'), (1, 'Alert'), (2, 'Critical'), (3, 'Error'), (4, 'Warning'), (5, 'Notice'), (6, 'Info'), (7, 'Debug')], db_index=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('is_config_change', models.BooleanField(db_index=True, default=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syslog_messages', to='inventory.device')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
